build/Jamfile.v2
The <link> attribute leads to errors.
=> use <library> tag for specifying needed libraries

include/boost/test/test_tools.hpp
Change b41a9354e9127e77d19a1b5c975c33729b033218 introduced regression failures due to preprocessor errors with respect to the && operator, leading to the following error:
../boost/test/test_tools.hpp:50:87: error: operator '&&' has no right operand
#if !BOOST_PP_VARIADICS || ((__cplusplus >= 201103L) && BOOST_NO_CXX11_VARIADIC_MACROS)
=> Fix feature test of BOOST_NO_CXX11_VARIADIC_MACROS

include/boost/test/tools/floating_point_comparison.hpp
My floating point type is not implicitly convertible from literal 0. close_at_tolerance should work with it as well.
=> close_at_tolerance: changed t >= 0 to t >= FPT(0)

include/boost/test/tools/floating_point_comparison.hpp
The MPL header file needs to be correctly included. This is necessary for upcoming type_traits version 2, which does not depend on MPL anymore.
=> Add needed MPL header file.

doc/closing_chapters/faq.qbk, doc/examples/decorator_01.output, doc/introduction/5min_primer.qbk, doc/introduction/how_to_read.qbk, doc/introduction/introduction.qbk, doc/introduction/overview.qbk, doc/snippet/snippet12.cpp, doc/test.qbk, doc/testing_tools/testing_tools_summary.qbk, doc/tutorial_new_year_resolution.qbk, doc/usage_recommandations.qbk
THe Introduction is now shorter. I removed one tutorial (it is in a non-included qbk file), and moved another one into Practical Usage Recommendations.
=> Doc: simpler introduction

doc/examples/decorator_01.output, include/boost/test/tools/floating_point_comparison.hpp, include/boost/test/tools/fpc_op.hpp, include/boost/test/tools/fpc_tolerance.hpp
Changed the occurences of FPT() to FPT(0). Since we expect a construction from int anyway,
and since the previous implementation assumed that the default constructor initializes to
numeric vaue zero, the change appears uncontroversial. What we gain, is that the default
ctor is no longer required. The FP algos work for non-default-constructible types.
=> FPT() --> FPT(0)bb

include/boost/test/tools/floating_point_comparison.hpp, include/boost/test/tools/fpc_op.hpp
Prior to this change, in floating-point computations, in the case
where we work for types where std::numeric_limits are not specialized,
funcitons min() and max() from std::numeric_limits<FPT> are nonetheless
instantiated and return FPT(0). While the result is never used in run-time,
this may still trigger a compile-time failure.
After this change, the paths for the cases where std::numeric_limits are not
specialized are handled by separate specializations rather than run-time if
statements.
=> Don't use std::numeric_limits when is_specialized is false

include/boost/test/tools/detail/tolerance_manip.hpp
Rationale:
Because we are not using the literal of type double, we avoid the bug where `FTP(0.01)` is evaluated as `FTP(int(0.01))` for FPT types that do not offer a conversion from `double`.
I do not use an explicit cast `v / FPT(100)` in order to allow the compiler to see that we are dividing by the integer, and engage optimizations for that case, if any.
By `v / 100` I require that conversion from int to FPT is implicit, and thereby avoid executing explicit constructors, which may have non-conversion semantics.
To the best of my knowledge, `v / 100` is not less accurate than `v * 0.01`. It may be slower, but given that this is evaluated in BOOST_TEST, which does lots of ops on IO streams, this should be negligible; plus, we are affecting only a percentage tolerance manipulator -- not …
=> v * FTP(0.01)  -->  v / 100

include/boost/test/tools/fpc_op.hpp
With this change we get a *desired* compile time failure when we are passed type `T` that is not implicitly convertible from `int` but is explicitly convertible. Now, we make an implicit conversion from `int` a requirement and refuse to compile otherwise.
This addresses an issue where the user gives us a type `T` with non-intuitive construction from `int`.
=> Changed v == T(0)  to  v == 0

test/Jamfile.v2
As an illustration, I configured three examples from documentation, so that they are only compiled when support for variadic macros is present on the compiler. I am using a feature from Boost.Config: http://www.boost.org/doc/libs/1_58_0/libs/config/doc/html/boost_config/build_config.html
It uses predefined platform macros (rather than tester name) to detect the availability of the feature.
=> testing: run tests conditionally

include/boost/test/detail/throw_exception.hpp, include/boost/test/impl/execution_monitor.ipp
Boost.Test used to support building with -fno-exceptions on GCC, this patch reinstates that support.
=> Fix broken support for building with -fno-exceptions on GCC.

doc/testing_tools/boost_test_universal_macro.qbk
The warning is closed in the previous line.
=> Remove extra close bracket.

include/boost/test/impl/execution_monitor.ipp
This fixes a build failure for GNU/Linux on powerpc, as described at https://bugzilla.redhat.com/show_bug.cgi?id=1262444
This is the same problem described at https://svn.boost.org/trac/boost/ticket/6767
=> Do not qualify <fenv.h> names that might be macros.

doc/README.md
A simple fix of the Markdown syntax for the link in the doc/README.md file.
=> Fix Markdown link format

doc/README.md
This corrects my previous (already merged) pull request #110.
I messed up the order of the different brackets and did not preview the
markdown before pushing. I'm very sorry.
This fix is tested in Atom's Markdown preview now and really fixes the
issue.
=> Correction of the previous syntax fix

include/boost/test/impl/framework.ipp
The problem was originally reported here:
https://github.com/boostorg/log/issues/51
=> Fix stdcerr file creation on shutdown

include/boost/test/utils/setcolor.hpp
Otherwise cross-compiling with MinGW on Linux
will fail.
=> Change Windows.h include to all-lowercase.

include/boost/test/data/test_case.hpp, include/boost/test/impl/framework.ipp, include/boost/test/parameterized_test.hpp, test/writing-test-ts/test_tools-test.cpp
This fixes numerous yet annoying compilation warnings:
```
note: #pragma message:
The practice of declaring the Bind placeholders (_1, _2, ...)
in the global namespace is deprecated.
Please use <boost/bind/bind.hpp> + using namespace boost::placeholders,
or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.
```
Apart from obscuring the output of compilation of libraries using Boost.Test, it may be troublesome on CI builds. On many CI services every line of log counts and if log dumps become too long, 
builds are terminated.
=> Avoid deprecated bind placeholders in global namespace

include/boost/test/impl/debug.ipp
The macro __linux is less portable and, for example, is not defined on
some architectures.
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=28314.
=> Use __linux__ instead of __linux.

include/boost/test/tree/observer.hpp
The parameter ```root_test_unit_id``` in the method ```test_start``` in the file ```boost/test/tree/observer.hpp``` causes unused parameter warning.
```
// a.cc
#define BOOST_TEST_MODULE your_test_module
#include <boost/test/included/unit_test.hpp>
BOOST_AUTO_TEST_CASE( test1 )
{
// reports 'error in "test1": test 2 == 1 failed'
BOOST_TEST( 2 == 1 );
}
```
```
g++ -Wall -Wextra -std=c++17 -g -O0 a.cc -I/home/ppm/src/boost -o a
In file included from /home/ppm/src/boost/boost/test/results_collector.hpp:19,
from /home/ppm/src/boost/boost/test/impl/junit_log_formatter.ipp:27,
from /home/ppm/src/boost/boost/test/included/unit_test.hpp:19,
from a.cc:6:
/home/ppm/src/boost/boost/test/tree/observer.hpp: In member function ‘virtual void boost::unit_test::test_observer::test_start(boost::unit_test:: …
```
=> Suppress the unused parameter warning for root_test_unit_id

include/boost/test/utils/timer.hpp
`__MACH__` matches any Mach-based OS, which means both macOS and GNU/Hurd; since the API used is really specific to macOS, then also check for `__APPLE__`.
This fixes the build on GNU/Hurd.
=> Use macOS API only on macOS

include/boost/test/impl/execution_monitor.ipp
Fixes usage of Boost.Test when compiling for web assembly with emscripten.
=> Web assembly has no support for an alternate stack.

include/boost/test/utils/setcolor.hpp
Apple Clang 14 warns that `sprintf` is deprecated. Replace with the new `boost::core::snprintf` for compatibility with pre-c++11 code, and across toolchains.
=> Fix for sprintf deprecation warning

include/boost/test/tools/old/impl.hpp
Implicit conversions are ill-formed so make them explicit
=> Fix check_is_close_t for C++23 `<stdfloat>` types

include/boost/test/utils/runtime/errors.hpp, include/boost/test/utils/runtime/parameter.hpp
The compiler-generated copy constructor and copy assignment operator are deprecated since C++11 on classes with user-declared destructors.
This change allows clean compilation with the -Wdeprecated-copy-dtor/-Wdeprecated-copy-with-user-provided-dtor flag.
=> Use BOOST_DEFAULTED_FUNCTION on empty destructors

include/boost/test/impl/execution_monitor.ipp
On some platforms uintptr_t is not the 'unsigned long' type. To avoid warnings the PRIxPTR format specifier is used
=> Use portable PRIxPTR printf format for uintptr_t

include/boost/test/impl/execution_monitor.ipp
Closes: #391 
glibc 2.2 - 2.17 required `__STDC_FORMAT_MACROS` to be defined for use of `PRIxPTR`. If necessary define and then undef after `<inttypes.h>` is included.
=> Fix definition of BOOST_TEST_PRIxPTR for glibc 2.2-2.17

include/boost/test/data/monomorphic/grid.hpp
Remove `std::move` on a temporary object to fix the following level 4 warning with Visual Studio 17.4 and later:
warning C5263: calling 'std::move' on a temporary object prevents copy elision
=> Fix MSVC compiler warning

include/boost/test/tools/detail/print_helper.hpp
- (Implicitly) printing a big enough type results in: "warning: overflow in expression; result is 2147483347 with type 'int' [-Winteger-overflow]".
- Fixed by promoting the calculation to 'std::streamsize'.
=> Fix overflow warning in `print_helper.hpp`. #398

include/boost/test/detail/config.hpp, include/boost/test/utils/named_params.hpp
On Visual Studio 16.9, the return was marked as unreachable because of the throw before
=> fix unreachable return compilation error

example/unit_test_example_16.cpp, include/boost/test/detail/global_typedef.hpp
This is the fix for https://github.com/boostorg/test/issues/430.
If the library is linked dynamically, clang built binary raises the arg_type_mismatch exception on reading configuration variables with type output_format or report_level.
I've added the test in unit_test_example_16.cpp but found that it was commented out from build and leave as it is.
=> Fix for the issue #430, arg_type_mismatch exception with dynamic link

include/boost/test/impl/test_tree.ipp, include/boost/test/tree/auto_registration.hpp
`tc_gen` is a macro in the linux UAPI, if included before `<boost/test/unit_test.hpp>` it causes compilation to fail.
=> Rename method arguments to avoid collision with linux UAPI macro

include/boost/test/data/size.hpp
If datasets are used, `<boost/test/data/size.hpp>` is also included, as can be seen in the [example](
https://www.boost.org/doc/libs/1_87_0/libs/test/doc/html/boost_test/tests_organization/test_cases/test_case_generation/datasets.html#boost_test.tests_organization.test_cases.test_case_generation.datasets.dataset_interface.example_descr). The class `class size_t` uses `std::size_t` in its API.
MSVC and Gcc indirectly have the definition of `std::size_t`, while Clang/LibC++ do not have this and a compiler error occurs. This fix will correct this.
=> Include <cstddef> in <boost/test/data/size.hpp>

include/boost/test/data/size.hpp, test/Jamfile.v2, test/framework-ts/dataset-size.cpp
Verify the constructor and increment/decrement operators
I wasn't sure https://github.com/boostorg/test/blob/10185327515e968ab01c9a5a4017c603777e4cd7/include/boost/test/data/size.hpp#L51 works as expected as the templated ctor might be preferred which would not copy the `is_inf`
The test also shows some inconsistencies in the over/underflow handling. It might be better to remove any operator taking a `std::size_t` which means those values will get converted to `data::size_t` and can be consistently handled.
=> Add test for the size_t class

.github/workflows/ci.yml, Jamfile.v2, build.jam, build/Jamfile.v2, doc/Jamfile.v2, example/Jamfile.v2, test/Jamfile.v2, tools/console_test_runner/Jamfile.v2
This is part of the effort to make the Boost libraries "modular" for build and consumption. See https://lists.boost.org/Archives/boost/2024/01/255704.php and https://github.com/grafikrobot/boost-b2-modular/blob/b2-modular/README.adoc for more information.
This PR depends on the following other PRs being merged to both develop and master branches of the respective repos:
- https://github.com/boostorg/boost/pull/854
This PR will be changed to ready for review, i.e. not draft, when the above are merged. Do not merge this one until that time.
=> Add support for modular build structure.

.github/workflows/ci.yml
We're in or past the GitHub actions deprecation window
=> Move ubuntu 20.04 runs into containers

.github/workflows/ci.yml, CMakeLists.txt
This PR allows the build to be configured to install only the Boost.Test headers required for using the [headers-only variant](https://www.boost.org/doc/libs/1_88_0/libs/test/doc/html/boost_test/usage_variants.html#boost_test.usage_variants.single_header) of the Unit Test Framework.
The [`README.md`](https://github.com/boostorg/cmake/blob/develop/README.md) file at https://github.com/boostorg/cmake should also be updated to mention this new Boost.Test-specific configuration variable.
=> cmake: Add `BOOST_TEST_HEADERS_ONLY` configuration variable

CMakeLists.txt
`cxx_std_11` requires CMake 3.8
=> Fix required CMake version
